### ISSUE TITLE
New vertical logo version

### ISSUE THREAD

**Issue by nienn** [readthedocs/guidelines#1]
Opening this issue to continue the discussion of a new version of the logo  that started here [readthedocs/blog#118](https://github.com/readthedocs/blog/pull/118).
It's meant for when a different aspect ratio is required.
<br>
<img src="https://user-images.githubusercontent.com/4049894/126691879-172d985a-eb34-4ddb-b01a-97f0b1e2afe8.jpg" alt="test"/>
<br>
<img src="https://user-images.githubusercontent.com/4049894/126691971-26f94c9e-e1ac-4087-886c-dcff8961f2f2.jpg" alt="test-2"/>
(how it would be seen over in Facebook with OpenGraph)

**Comment by agjohnson** [comment]
:+1: I like the format of this one, mostly because it's practical, given how we're using our other formats. There is definitely more room to be less conservative with our branding in the near future, but this will work great for now. Feel free to throw up a PR with a png, or png + svg if you were working with the svg.

A next iteration could definitely be more stylized. We tend to always use both logo and wordmark as white on dark grey or inverted. I'd love to find ways to use the logo/wordmark that weren't so ... monochromatic -- ie:

![image](https://user-images.githubusercontent.com/1140183/126699723-2f950dd6-9451-45bc-9d3c-265b181e3fca.png)

Some of this will depend on where we go with styles on landing pages and our main site, as this example is a bit bold for our current look and feel on any of our sites.

Anyways, feel free to throw around some ideas here, we can definitely continue playing with this and our wordmark/logo in general really.

**Comment by agjohnson** [comment]
I'd have to recreate this, the SVG didn't get pushed up.
